task_1:
  audio_path: C:/Users/hp/Desktop/PERSONALPROJECTS/AINewsAudible/podcast_sarvam.wav
  result_name: C:/Users/hp/Desktop/PERSONALPROJECTS/AINewsAudible/MuseTalk/results/tmp/output_943a4f815b2d4f5d82711a9e2be1f37f.mp4
  video_path: C:/Users/hp/Desktop/PERSONALPROJECTS/AINewsAudible/host.jpg
